# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'constellation_panel.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ConstellationWindow(object):
    def setupUi(self, ConstellationWindow):
        ConstellationWindow.setObjectName("ConstellationWindow")
        ConstellationWindow.resize(1250, 703)
        self.centralwidget = QtWidgets.QWidget(ConstellationWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textDisplay = QtWidgets.QTextBrowser(self.centralwidget)
        self.textDisplay.setGeometry(QtCore.QRect(240, 460, 731, 211))
        self.textDisplay.setObjectName("textDisplay")
        self.prevBtn = QtWidgets.QPushButton(self.centralwidget)
        self.prevBtn.setGeometry(QtCore.QRect(10, 200, 75, 201))
        font = QtGui.QFont()
        font.setPointSize(52)
        self.prevBtn.setFont(font)
        self.prevBtn.setObjectName("prevBtn")
        self.nextBtn = QtWidgets.QPushButton(self.centralwidget)
        self.nextBtn.setGeometry(QtCore.QRect(1160, 200, 75, 201))
        font = QtGui.QFont()
        font.setPointSize(52)
        self.nextBtn.setFont(font)
        self.nextBtn.setObjectName("nextBtn")
        self.mainWindowBtn = QtWidgets.QPushButton(self.centralwidget)
        self.mainWindowBtn.setGeometry(QtCore.QRect(10, 10, 31, 23))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.mainWindowBtn.setFont(font)
        self.mainWindowBtn.setObjectName("mainWindowBtn")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(0, 0, 1251, 681))
        self.graphicsView.setObjectName("graphicsView")
        self.graphicsView.raise_()
        self.textDisplay.raise_()
        self.prevBtn.raise_()
        self.nextBtn.raise_()
        self.mainWindowBtn.raise_()
        ConstellationWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(ConstellationWindow)
        QtCore.QMetaObject.connectSlotsByName(ConstellationWindow)

    def retranslateUi(self, ConstellationWindow):
        _translate = QtCore.QCoreApplication.translate
        ConstellationWindow.setWindowTitle(_translate("ConstellationWindow", "MainWindow"))
        self.textDisplay.setHtml(_translate("ConstellationWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">This is the text box that will contain descriptions and relevant information.</span></p></body></html>"))
        self.prevBtn.setText(_translate("ConstellationWindow", "<"))
        self.nextBtn.setText(_translate("ConstellationWindow", ">"))
        self.mainWindowBtn.setText(_translate("ConstellationWindow", "«"))


